# Multiclass classification using Deep Neural Networks

### Example: Use the OCR letter
### recognition dataset https://archive.ics.uci.edu/ml/datasets/letter+recognition

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [7]:
# 1. Load dataset
data = pd.read_csv("letter-recognition.data", header=None)

In [8]:
# 2. Split features & labels
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

In [9]:
# 3. Encode labels (A-Z → 0-25)
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
# 4. Convert to float
X = X.astype('float32')

In [11]:
# 5. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
# 6. Build DNN model (MULTICLASS)
model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(16,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(26, activation='softmax'))  # 26 classes (A-Z)

D:\software\anaconda\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
# 7. Compile model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
# 8. Train model
model.fit(X_train, y_train, epochs=25, batch_size=32)

Epoch 1/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 898us/step - accuracy: 0.4679 - loss: 1.9335
Epoch 2/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7232 - loss: 1.0062
Epoch 3/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7646 - loss: 0.8153
Epoch 4/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7944 - loss: 0.7054
Epoch 5/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.8191 - loss: 0.6199
Epoch 6/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8351 - loss: 0.5649
Epoch 7/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.8472 - loss: 0.5139
Epoch 8/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8550 - loss: 0.4850
Epoch 9/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8639 - loss: 0.4492
Epoch 10/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.8709 - loss: 0.4259
Epoch 11/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8790 - loss: 0.3981
Epoch 12/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8865 - loss: 0.3772
Epoch 13/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8900 - loss: 0.3613
Epoch 14/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.8916 - loss: 0.3456
Epoch 15/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8962 - loss: 0.3292
Epoch 16/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.9006 - loss: 0.3197
Epoch 17/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.9031 - loss: 0.3092
Epoch 18/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.9087 - loss: 0.2934
Epoch 19/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.9099 - loss: 0.2853
Epoch 20/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.9120 - loss: 0.2759
Epoch 21/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.9153 - loss: 0.2673
Epoch 22/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.9133 - loss: 0.2637
Epoch 23/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.9168 - loss: 0.2568
Epoch 24/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.9215 - loss: 0.2454
Epoch 25/25
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.9233 - loss: 0.2398

In [15]:
# 9. Evaluate model
loss, acc = model.evaluate(X_test, y_test)
print("Accuracy:", acc)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.9082 - loss: 0.2903
Accuracy: 0.9082499742507935

In [16]:
data.describe()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [17]:
data.head()

  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0  T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1  I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2  D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3  N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4  G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10

In [18]:
data.tail()

      0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
19995  D   2   2   3   3   2   7   7   7   6   6   6   4   2   8   3   7
19996  C   7  10   8   8   4   4   8   6   9  12   9  13   2   9   3   7
19997  T   6   9   6   7   5   6  11   3   7  11   9   5   2  12   2   4
19998  S   2   3   4   2   1   8   7   2   6  10   6   8   1   9   5   8
19999  A   4   9   6   6   2   9   5   3   1   8   1   8   2   7   2   8

In [3]:
data.shape

NameError: name 'data' is not defined